### ISSUE TITLE
seems this can't compile anymore after changes to utf_range being made header only

### ISSUE THREAD

**Issue by qwertynat** [beached/json_to_cpp#1]
on a fresh clone this fails to link, it is looking for -utf_range -ltemp_file 

which are now header only i think

**Comment by beached** [comment]
Ill see what I can do to get it building.  The dependent code bases have had a lot of changes and I think for now I need to fix the version used to an older revision.   Once v2 is done with daw_json_link I planned to make some big changes to json_to_cpp so that it can generate newer binding code.

**Comment by beached** [comment]
Should be fixed now.  utf_range was made optionally header only outside "this" project nothing uses the binary and it was adding build time.  And temp_file was made header only but it wasn't relected here.  Was able to do a clean make build

**Comment by qwertynat** [comment]
gets further, however a (final) error 

[100%] Linking CXX executable json_to_cpp
/usr/bin/ld: /home/nathan/src//TEST/json_to_cpp/build/install/lib/libutf_string.a(daw_utf_string.cpp.o): in function `daw::utf_string::to_u32string[abi:cxx11]() const':
daw_utf_string.cpp:(.text+0x54f): undefined reference to `daw::range::utf_range::to_u32string[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/json_to_cpp.dir/build.make:120: json_to_cpp] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/json_to_cpp.dir/all] Error 2
gmake: *** [Makefile:161: all] Error 2

**Comment by beached** [comment]
did you clean the cmake build, might need to recreate the build folder?  there were defines added to two projects in their cmake config.

**Comment by qwertynat** [comment]
just tried my desktop instread of laptop, both, fedora32. same error.

**Comment by beached** [comment]
Found it, I don't know how it worked but MacOS is odd too.  It was missing a target library.  Was able to make it work in ubuntu after seeing that error

Probably why my other projects have got CI and this one will in the future too

**Comment by qwertynat** [comment]
yeah all good here as well.  

many thanks!

**Comment by beached** [comment]
Awesome.  The plan is a rewrite using daw_json_link as the basis, it is much faster while the current parse_json dep is really old and slow.
