### ISSUE TITLE
can/t compile with boost 1.74

### ISSUE THREAD

**Issue by ghost** [beached/json_to_cpp#2]
Full log attached

[log.txt](https://github.com/beached/json_to_cpp/files/6488430/log.txt)

**Comment by beached** [comment]
This is fixed with two updates.
The first is https://github.com/beached/header_libraries/commit/4af6bf85c542dd758462c57e7c5190a405a77166

**Comment by beached** [comment]
The second is 4d2c3b57b594bb84819edaa3f01b6ab4f0f8353a

That fixes the build issue
